# Generated by Django 4.2.6 on 2023-10-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='mount',
            new_name='amount',
        ),
    ]
